name: '.NET Core Build, Test And Deploy'

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Restore, Build, Test
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
  
      - name: Restore
        run: dotnet restore
  
      - name: Build
        run: dotnet build --configuration Release --no-restore
  
      - name: Test
        run: dotnet test --no-restore

      # Deploy
      - name: Deploy Over SSH
      - run: ssh user@127.0.0.1 "sudo cp -rlf app/* /var/api/international-cards-svc/"
      - run: ssh user@127.0.0.1 "sudo systemctl restart international-cards.service"